name: Java CI and Health Check

on: [pull_request]

jobs:
  build-and-health-check:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: zx123123
        ports:
          - 3306:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Wait for MySQL
        run: |
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh mysql:3306 --timeout=60
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean install
          mvn -B package --file pom.xml
      # using maven to run spring boot application
      - name: Run health check
        env:
          DATABASE_NAME: csye6225
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: zxs123123
          DATABASE_ENDPOINT: 127.0.0.1
        run: |
          mvn spring-boot:run
          STATUS_CODE=$(curl --write-out "%{http_code}\n" --silent --output /dev/null "http://localhost:8080/healthz")
        
          # Check if the status code is 200
          if [[ "$STATUS_CODE" -ne 200 ]] ; then
          echo "Health check failed with status code $STATUS_CODE"
          exit 1
          else
          echo "Health check passed with status code $STATUS_CODE"
          fi



