name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: 'latest'

      - name: Packer Init
        run: |
          cd ./packer
          packer init ami.us-west-2.pkr.hcl

      - name: Build AMI
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          DEMO_ACCOUNT_ID: ${{ vars.DEMO_ACCOUNT_ID }}
          INSTANCE_TYPE: ${{ vars.INSTANCE_TYPE }}
          SOURCE_AMI: ${{ vars.SOURCE_AMI }}
          SSH_USERNAME: ${{ vars.SSH_USERNAME }}
          SUBNET_ID: ${{ vars.SUBNET_ID }}
          VOLUME_SIZE: ${{ vars.VOLUME_SIZE }}
          VOLUME_TYPE: ${{ vars.VOLUME_TYPE }}
        run: |
          cd ./packer
          VOLUME_SIZE_INT=$(printf '%d' "$VOLUME_SIZE")
          packer build -var "aws_region=${{ env.AWS_REGION }}" \
            -var "demo_account_id=${{ env.DEMO_ACCOUNT_ID }}" \
            -var "instance_type=${{ env.INSTANCE_TYPE }}" \
            -var "source_ami=${{ env.SOURCE_AMI }}" \
            -var "ssh_username=${{ env.SSH_USERNAME }}" \
            -var "subnet_id=${{ env.SUBNET_ID }}" \
            -var "volume_size=${VOLUME_SIZE_INT}" \
            -var "volume_type=${{ env.VOLUME_TYPE }}" \
            ami.us-west-2.pkr.hcl

      - name: install jq
        run: |
          sudo apt-get install jq

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
          aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
          aws configure set region ${{ vars.AWS_REGION }} && \
          aws configure set default.output_format json

      - name: Create Launch Template Version
        run: |
          aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
          aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
          aws configure set region ${{ vars.AWS_REGION }} && \
          aws configure set default.output_format json
          ami_id=$(cat output-ami-id.txt)
          aws ec2 create-launch-template-version --launch-template-name ${{ vars.LAUNCH_TEMPLATE_NAME }} --source-version '$Latest' --launch-template-data '{"ImageId": "'$ami_id'"}'

      - name: Refresh Auto Scaling Group
        run: |
          aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
          aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
          aws configure set region ${{ vars.AWS_REGION }} && \
          aws configure set default.output_format json
          aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ vars.AUTO_SCALING_GROUP_NAME }}

      - name: Wait for Instance Refresh
        run: |
          aws configure set aws_access_key_id ${{ secrets.DEMO_ACCESS_KEY_ID }} && \
          aws configure set aws_secret_access_key ${{ secrets.DEMO_SECRET_ACCESS_KEY }} && \
          aws configure set region ${{ vars.AWS_REGION }} && \
          aws configure set default.output_format json
          completed="false"
          while [ "$completed" != "true" ]; do
            status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ vars.ASG_NAME }} --query 'InstanceRefreshes[0].Status' --output text)
            if [ "$status" == "Successful" ]; then
              completed="true"
            elif [ "$status" == "Failed" ]; then
              echo "Instance refresh failed"
              exit 1
            fi
            sleep 20
          done
            

