name: Packer CI And Status Check

on:
  pull_request:
    branches: [ main ]

jobs:
  packer-ci:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      DEMO_ACCOUNT_ID: ${{ vars.DEMO_ACCOUNT_ID }}
      INSTANCE_TYPE: ${{ vars.INSTANCE_TYPE }}
      SOURCE_AMI: ${{ vars.SOURCE_AMI }}
      SSH_USERNAME: ${{ vars.SSH_USERNAME }}
      SUBNET_ID: ${{ vars.SUBNET_ID }}
      VOLUME_SIZE: ${{ vars.VOLUME_SIZE }}
      VOLUME_TYPE: ${{ vars.VOLUME_TYPE }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Packer Init
        run: |
          cd ./packer
          packer init ami.us-west-2.pkr.hcl

      - name: Debugging - Print environment variables
        run: |
          echo "AWS_REGION: ${{ env.AWS_REGION }}"
          echo "DEMO_ACCOUNT_ID: ${{ env.DEMO_ACCOUNT_ID }}"
          echo "INSTANCE_TYPE: ${{ env.INSTANCE_TYPE }}"
          echo "SOURCE_AMI: ${{ env.SOURCE_AMI }}"
          echo "SSH_USERNAME: ${{ env.SSH_USERNAME }}"
          echo "SUBNET_ID: ${{ env.SUBNET_ID }}"
          echo "VOLUME_SIZE: ${{ env.VOLUME_SIZE }}"
          echo "VOLUME_TYPE: ${{ env.VOLUME_TYPE }}"

      - name: Debugging - Print environment variables
        run: |
          echo "VOLUME_SIZE: $VOLUME_SIZE"

      - name: Validate and Convert VOLUME_SIZE to Integer
        run: |
          if ! [[ "$VOLUME_SIZE" =~ ^[0-9]+$ ]]; then
            echo "VOLUME_SIZE is not a number. Converting to a number."
            VOLUME_SIZE=8  
          fi
          echo "VOLUME_SIZE=$VOLUME_SIZE" >> $GITHUB_ENV

      - name: Packer Format
        run: |
          packer fmt ./packer/ami.us-west-2.pkr.hcl
          if [ $? -eq 2 ]; then
            echo "Packer fmt has detected errors"
            exit 1
          fi

      - name: Packer Validate
        run: |
          VOLUME_SIZE_INT=$((VOLUME_SIZE + 0))
          packer validate -var "aws_region=${{ env.AWS_REGION }}" \
            -var "demo_account_id=${{ env.DEMO_ACCOUNT_ID }}" \
            -var "instance_type=${{ env.INSTANCE_TYPE }}" \
            -var "source_ami=${{ env.SOURCE_AMI }}" \
            -var "ssh_username=${{ env.SSH_USERNAME }}" \
            -var "subnet_id=${{ env.SUBNET_ID }}" \
            -var "volume_size=${{ env.VOLUME_SIZE_INT }}" \
            -var "volume_type=${{ env.VOLUME_TYPE }}" \
            ./packer/ami.us-west-2.pkr.hcl
