name: Packer CI And Status Check

on:
  pull_request:
    branches: [ main ]

jobs:
  packer-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Packer Init
        run: |
          cd ./packer
          packer init ami.us-west-2.pkr.hcl

      - name: Debugging - Print environment variables
        run: |
          echo "VOLUME_SIZE: $VOLUME_SIZE"

      - name: Validate and Convert VOLUME_SIZE to Integer
        run: |
          if ! [[ "$VOLUME_SIZE" =~ ^[0-9]+$ ]]; then
            echo "VOLUME_SIZE is not a number. Converting to a number."
            VOLUME_SIZE=0  # 或其他默认数字值
          fi
          echo "VOLUME_SIZE=$VOLUME_SIZE" >> $GITHUB_ENV

      - name: Packer Format
        run: |
          packer fmt ./packer/ami.us-west-2.pkr.hcl
          if [ $? -eq 2 ]; then
            echo "Packer fmt has detected errors"
            exit 1
          fi

      - name: Packer Validate
        run: |
          packer validate -var "aws_region=$AWS_REGION" \
            -var "demo_account_id=$DEMO_ACCOUNT_ID" \
            -var "instance_type=$INSTANCE_TYPE" \
            -var "source_ami=$SOURCE_AMI" \
            -var "ssh_username=$SSH_USERNAME" \
            -var "subnet_id=$SUBNET_ID" \
            -var "volume_size=$VOLUME_SIZE" \
            -var "volume_type=$VOLUME_TYPE" \
            ./packer/ami.us-west-2.pkr.hcl
